# Dynamic App Icons Configuration
# This file defines the available app icons that can be changed dynamically

# Default icon identifier (optional)
# If specified, this icon will be used as the default when resetting
default_icon: "diwali"

# Icon definitions
icons:
  # Simple format: just a path to the icon file
  levelup:
    path: "assets/images/levelup.png"
    label: "Level Up"
    description: "The default app icon"

  christmas:
    path: "assets/images/christmas.png"
    label: "Christmas Icon"
    description: "Festive Christmas-themed app icon"
  
  # Another example
  halloween:
    path: "assets/images/halloween.png"
    label: "Halloween Icon"
    description: "Spooky Halloween-themed app icon"
  
  # Minimal format (just the path)
  diwali: "assets/images/diwali.png"
