default_icon: "default"

icons:
  default:
    path: "assets/images/launcher_icon.png"
    label: "Default Icon"
    description: "The default app icon"

  independance:
    path: "assets/images/card2.png"
    label: "Christmas Icon"
    sizes:
      xxhdpi: "assets/images/prepaidCard_success.png"
    description: "Festive Christmas-themed app icon"

  payme:
    path: "assets/images/gift.png"
    label: "Halloween Icon"
    description: "Spooky Halloween-themed app icon"

  diwali:
    path: "assets/images/gift.png"
    label: "Diwali Icon"
    description: "Spooky Halloween-themed app icon"
